server:
  port: 9000
spring:
  application:
    name: admin-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.128:8999
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:9100
      scg:
        fallback:
          mode: response
          response-body: '{"code":403,"mes":"被限流"}'
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #cors跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE

      discovery:
        locator:
          enabled: false # 是否启动自动识别nacos服务，开启的话，下面路由就不用写了，会自动断言服务名（IP/服务名/路径），但不太推荐使用，阅读性也差
      # 路由数组[路由：指定当请求满足什么条件的时候转到哪个微服务]
      routes:
        # 平台管理 当前路由的唯一标识
        - id: admin
          # 请求要转发到的地址 lb是nacos本地负载均衡策略
          uri: lb://admin
          # 路由的优先级,数字越小级别越高
          order: 1
          # 断言(路由转发要满足的条件) （https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gateway-request-predicates-factories）
          predicates:
            # 当请求路径满足Path指定的规则时,才进行路由转发
            - Path=/admin/**  # http://localhost:9420/admin/api/v1/tag/list -->http://localhost:9000/api/v1/tag/list
            # 自定义断言检查
            # - CheckAuth=coisini
          # 过滤器，请求在传递过程中可以通过过滤器对其进行一定的修改 https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gatewayfilter-factories
          filters:
            # 前面加admin的后缀都去掉，匹配后面的路径
            - StripPrefix= 1
            # 添加请求头
            #- AddRequestHeader=X-Request-color, red
            # 添加前缀,对应微服务需要配置context-path
            #- PrefixPath=/admin
            # 重定向
            #- RedirectTo=302, https://coisini.cn
        # user微服务管理
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
        # system微服务管理
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix= 1
